# Generated by Django 2.2 on 2020-08-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='worked_now',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
